### ISSUE TITLE
Scrum projeto E

### ISSUE THREAD

**Issue by rafaelcorsi** [marcosvds/Forknife#144]
https://github.com/marcosvds/Forknife/blob/59db21dd269065d0b5cf6a5d2ce3c148708c1808/Projetos/E-Assembly/SCRUM_MASTER.json#L2

Pessoal não sei quem foi o scrum do projeto E, pq não preencheu o arquivo .json. 

Envio por aqui o formulário que ele deve preencher:

https://forms.gle/P6Fs86Q8NTsSAjFz7

att,

**Comment by enricofd** [comment]
Desculpe professor, acabei esquecendo. Ja preenchi o formulario!
